### ISSUE TITLE
Hay algún demo de como funciona esto?

### ISSUE THREAD

**Issue by sebacruz** [CodelyTV/figma-plugin-structurer#4]

**Comment by sebacruz** [comment]
Hola?

**Comment by JavierCane** [comment]
Puedes instalar el plug-in desde el marketplace de Figma: https://www.figma.com/community/plugin/1151113258187986741/Codely-Structurer

mins vez instalado, simplemente es hacer click en el menú de plug-ins y ejecutarlo 😊

Falta por documentar esto en el readme. Si te animas a hacer una PR, más que bienvenida 🙌
